# this config file contains all config fields with comments
# NOTE: this is not a particularly useful config file
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
      endpoint = ["http://kind-registry:5000"]
# 1 control plane node and 1 workers
nodes:
  # the control plane node config
  - role: control-plane
  # the workers workers
  - role: worker
    extraPortMappings:
      - containerPort: 30001
        hostPort: 30001
        listenAddress: "0.0.0.0"
      - containerPort: 30002
        hostPort: 30002
        listenAddress: "0.0.0.0"
      - containerPort: 30003
        hostPort: 30003
        listenAddress: "0.0.0.0"
      - containerPort: 30004
        hostPort: 30004
        listenAddress: "0.0.0.0"
      - containerPort: 30005
        hostPort: 30005
        listenAddress: "0.0.0.0"