apiVersion: v1
kind: Service
metadata:
  name: container-two-service
  namespace: container-challenges
  labels:
    app: ContainerTwo
spec:
  type: NodePort
  selector:
    app: ContainerTwo
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002