apiVersion: v1
kind: Service
metadata:
  name: container-five-service
  namespace: container-challenges
  labels:
    app: ContainerFive
spec:
  type: NodePort
  selector:
    app: ContainerFive
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005