apiVersion: v1
kind: Service
metadata:
  name: container-three-service
  namespace: container-challenges
  labels:
    app: ContainerThree
spec:
  type: NodePort
  selector:
    app: ContainerThree
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30003