apiVersion: v1
kind: Service
metadata:
  name: container-one-service
  namespace: container-challenges
  labels:
    app: ContainerOne
spec:
  type: NodePort
  selector:
    app: ContainerOne
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001