apiVersion: v1
kind: Service
metadata:
  name: container-four-service
  namespace: container-challenges
  labels:
    app: ContainerFour
spec:
  type: NodePort
  selector:
    app: ContainerFour
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004